services:
  backend:
    container_name: mealplanner_backend
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=group15
      - CELERY_BROKER_URL=amqp://guest:guest@message_queue:5672//
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=it4788
      - POSTGRESQL_DBNAME=mealplanner_db
      - POSTGRESQL_HOST=database
      - POSTGRESQL_PORT=5432
      - MAIL_USERNAME=minhnguyenhai26032003@gmail.com
      - MAIL_PASSWORD=xsurrgjlrrgexjsg
      - FIREBASE_CREDENTIALS_PATH=secrets/serviceAccount.json
      - FIREBASE_STORAGE_BUCKET=meal-plan-app-acf97.firebasestorage.app
    depends_on:
      database: 
        condition: service_healthy
      message_queue:
        condition: service_healthy

  database:
    container_name: mealplanner_database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=it4788
      - POSTGRES_DB=mealplanner_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mealplanner_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  message_queue:
    container_name: mealplanner_message_queue
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5