"""check check

Revision ID: 0681d8553c74
Revises: d30cebc6ac28
Create Date: 2024-11-21 13:32:51.295861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0681d8553c74'
down_revision = 'd30cebc6ac28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('confirm_token', sa.String(length=255), nullable=True))
    op.drop_constraint('tokens_reset_code_key', 'tokens', type_='unique')
    op.create_unique_constraint(None, 'tokens', ['confirm_token'])
    op.drop_column('tokens', 'reset_code')
    op.drop_column('tokens', 'reset_code_expires_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('reset_code_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tokens', sa.Column('reset_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tokens', type_='unique')
    op.create_unique_constraint('tokens_reset_code_key', 'tokens', ['reset_code'])
    op.drop_column('tokens', 'confirm_token')
    # ### end Alembic commands ###
