"""Remove unique constraint in column 'name' in table 'units'

Revision ID: 131bb5450bfd
Revises: a1decc9ae3ee
Create Date: 2024-12-10 11:32:39.666242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131bb5450bfd'
down_revision = 'a1decc9ae3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint('units_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_unique_constraint('units_name_key', ['name'])

    # ### end Alembic commands ###
