"""update fridgeItem

Revision ID: 15d11881b494
Revises: 72e17243bfcb
Create Date: 2024-12-07 11:46:21.046116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d11881b494'
down_revision = '72e17243bfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'fridge_items',
    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now())
)
    op.alter_column('fridge_items', 'updated_at', server_default=None)
    op.add_column('fridge_items', sa.Column('status', sa.String(length=10), nullable=True))
    op.execute("UPDATE fridge_items SET status = 'active'")
    op.alter_column('fridge_items', 'status', nullable=False)
    op.create_foreign_key(None, 'recipes', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('fridge_items', 'status')
    op.drop_column('fridge_items', 'updated_at')
    # ### end Alembic commands ###
