"""add name description

Revision ID: 1ae83483db9b
Revises: dacb32321fa4
Create Date: 2024-12-14 21:47:05.479975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae83483db9b'
down_revision = 'dacb32321fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan_foods', sa.Column('food_id', sa.String(length=36), nullable=False))
    op.add_column('meal_plans', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('meal_plans', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('meal_plans', 'meal_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('meal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('meal_plans', 'description')
    op.drop_column('meal_plans', 'name')
    op.drop_column('meal_plan_foods', 'food_id')
    # ### end Alembic commands ###
