"""add new attribute to food

Revision ID: 48bed66a7613
Revises: 8d3f40d75346
Create Date: 2024-12-06 00:49:43.785297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bed66a7613'
down_revision = '8d3f40d75346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('create_by', sa.String(length=36), nullable=False))
    op.add_column('foods', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('foods', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('foods', sa.Column('note', sa.String(length=255), nullable=False))
    op.add_column('foods', sa.Column('status', sa.String(length=10), nullable=False))
    op.create_foreign_key(None, 'foods', 'users', ['create_by'], ['id'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.drop_column('foods', 'status')
    op.drop_column('foods', 'note')
    op.drop_column('foods', 'updated_at')
    op.drop_column('foods', 'type')
    op.drop_column('foods', 'create_by')
    # ### end Alembic commands ###
