"""hehe

Revision ID: 53423d18478f
Revises: 6ce1e8a359b9
Create Date: 2024-12-06 23:51:01.972627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53423d18478f'
down_revision = '6ce1e8a359b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_type_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_type_fkey', 'categories', 'groups', ['type'], ['id'])
    # ### end Alembic commands ###
