"""remove relationship foods_recipes

Revision ID: 57921567c771
Revises: edf508a592e0
Create Date: 2024-12-26 00:08:44.955402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '57921567c771'
down_revision = 'edf508a592e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_foods', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    #insert id column
    conn = op.get_bind()
    conn.execute(text("CREATE SEQUENCE IF NOT EXISTS recipe_foods_id_seq"))
    conn.execute(text("UPDATE recipe_foods SET id = nextval('recipe_foods_id_seq')"))
    op.alter_column('recipe_foods', 'id',
                existing_type=sa.Integer(),
                nullable=False)

    op.add_column('meal_plan_foods', sa.Column('unit_id', sa.String(length=36), nullable=True))
    op.alter_column('meal_plan_foods', 'food_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('recipe_foods', sa.Column('food_name', sa.String(length=255), nullable=True))
    op.add_column('recipe_foods', sa.Column('unit_id', sa.String(length=36), nullable=True))
    op.add_column('recipe_foods', sa.Column('unit_name', sa.String(length=50), nullable=True))
    op.drop_constraint('recipe_foods_pkey', 'recipe_foods', type_='primary')

    #Thiết lập lại khóa chính mới chỉ với cột 'id'
    op.alter_column('recipe_foods', 'food_id', nullable=True)
    op.create_primary_key('recipe_foods_pkey', 'recipe_foods', ['id'])
    op.alter_column('recipe_foods', 'food_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_unique_constraint('uq_recipe_food', 'recipe_foods', ['recipe_id', 'food_name'])

def downgrade():
    # Xóa khóa chính mới
    op.drop_constraint('recipe_foods_pkey', 'recipe_foods', type_='primary')
    
    # Khôi phục khóa chính cũ (giả định rằng khóa chính ban đầu bao gồm 'recipe_id' và 'food_id')
    op.create_primary_key('recipe_foods_pkey', 'recipe_foods', ['recipe_id', 'food_id'])
    
    # Xóa cột 'id' vừa thêm
    op.drop_column('recipe_foods', 'id')
    
    # Xóa unique constraint vừa thêm
    op.drop_constraint('uq_recipe_food', 'recipe_foods', type_='unique')
    
    # Khôi phục lại thuộc tính NOT NULL cho 'food_id'
    op.alter_column('recipe_foods', 'food_id', nullable=False)

    # Xóa các cột bổ sung khác
    op.drop_column('recipe_foods', 'food_name')
    op.drop_column('recipe_foods', 'unit_id')
    op.drop_column('recipe_foods', 'unit_name')
    op.drop_column('meal_plan_foods', 'unit_id')

    # (Tùy chọn) Nếu đã tạo sequence, bạn có thể xóa sequence (nếu không còn sử dụng)
    conn = op.get_bind()
    conn.execute(text("DROP SEQUENCE IF EXISTS recipe_foods_id_seq"))
