"""add some name to shopping

Revision ID: 7c16761129a9
Revises: 290e90beb5db
Create Date: 2024-12-29 11:51:02.522533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c16761129a9'
down_revision = '290e90beb5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('assigned_to_username', sa.String(length=100), nullable=True))
    op.add_column('shopping_tasks', sa.Column('food_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('shopping_tasks', 'food_name')
    op.drop_column('shopping_lists', 'assigned_to_username')
    # ### end Alembic commands ###
