"""Remove constraint unique for column 'group_name' in table 'groups'

Revision ID: 8d3f40d75346
Revises: f65abcfd12c4
Create Date: 2024-12-02 19:10:58.035046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3f40d75346'
down_revision = 'f65abcfd12c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint('groups_group_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_unique_constraint('groups_group_name_key', ['group_name'])

    # ### end Alembic commands ###
