"""Remove field 'is_activate', add new field 'is_deleted' and remove unique constraint in columns 'email', 'username' in table 'users'

Revision ID: b31618a0dd59
Revises: cdff69d3aa41
Create Date: 2024-12-28 19:19:13.272763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'b31618a0dd59'
down_revision = 'cdff69d3aa41'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.execute("UPDATE users SET is_deleted = FALSE WHERE is_deleted IS NULL")
    op.alter_column('users', 'is_deleted', nullable=False)


def downgrade():
    
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.execute("UPDATE users SET is_active = FALSE WHERE is_active IS NULL")
    op.alter_column('users', 'is_active', nullable=False)
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
