"""Add 3 fields 'reset_token', 'reset_code', 'reset_code_expires_at' into table 'tokens'

Revision ID: d46ecd0fbd36
Revises: edf508a592e0
Create Date: 2024-12-23 16:52:04.383896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46ecd0fbd36'
down_revision = 'edf508a592e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['reset_token'])
        batch_op.create_unique_constraint(None, ['reset_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reset_code_expires_at')
        batch_op.drop_column('reset_code')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
