"""change some ln n_n

Revision ID: dacb32321fa4
Revises: 9f1d2909c863
Create Date: 2024-12-14 15:14:25.136774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacb32321fa4'
down_revision = '9f1d2909c863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan_foods', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('meal_plan_foods', sa.Column('food_name', sa.String(length=255), nullable=False))
    op.add_column('meal_plan_foods', sa.Column('unit', sa.String(length=50), nullable=True))
    op.add_column('meal_plan_foods', sa.Column('quantity', sa.Float(), nullable=False))
    op.create_unique_constraint('uq_plan_food', 'meal_plan_foods', ['plan_id', 'food_name'])
    op.drop_constraint('meal_plan_foods_food_id_fkey', 'meal_plan_foods', type_='foreignkey')
    op.drop_column('meal_plan_foods', 'food_id')
    op.add_column('meal_plan_recipes', sa.Column('servings', sa.Float(), nullable=False))
    op.add_column('meal_plans', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('meal_plans', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plans', 'is_deleted')
    op.drop_column('meal_plans', 'updated_at')
    op.drop_column('meal_plan_recipes', 'servings')
    op.add_column('meal_plan_foods', sa.Column('food_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key('meal_plan_foods_food_id_fkey', 'meal_plan_foods', 'foods', ['food_id'], ['id'])
    op.drop_constraint('uq_plan_food', 'meal_plan_foods', type_='unique')
    op.drop_column('meal_plan_foods', 'quantity')
    op.drop_column('meal_plan_foods', 'unit')
    op.drop_column('meal_plan_foods', 'food_name')
    op.drop_column('meal_plan_foods', 'id')
    # ### end Alembic commands ###
