"""Delete field 'status' in table 'foods'

Revision ID: edf508a592e0
Revises: 00fd00304df6
Create Date: 2024-12-22 22:22:37.171515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf508a592e0'
down_revision = '00fd00304df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
