"""Add 3 new fields 'creator_username', 'category_name', 'unit_name' in table 'foods'

Revision ID: f69f578f9e06
Revises: b31618a0dd59
Create Date: 2024-12-28 22:31:09.936444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69f578f9e06'
down_revision = 'b31618a0dd59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unit_name', sa.String(), nullable=True))
        batch_op.alter_column('create_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('create_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('unit_name')
        batch_op.drop_column('category_name')
        batch_op.drop_column('creator_username')

    # ### end Alembic commands ###
